export const dummyProductList = () => [
  {
    id: 1,
    product_name: "Front Load",
    product_abbreviation: "FL",
    product_line: "D310",
    status: 1,
    product_description: "Description",
    call_script: [
      {
        sl: 1,
        level:
          "May I ask if you are looking to rent for a jobsite or an event?",
        field_type: "option",
        field_option: ["Event", "Jobsite"],
        answer: "",
      },
      {
        sl: 2,
        level: "How many attendees do you plan on having?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 3,
        level: "What is the duration and day of your event?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 4,
        level:
          "Will you have a need for hand wash station or handicap accessible unit?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 5,
        level:
          "Will you have a need for hand wash station or handicap accessible unit?",
        field_type: "option",
        field_option: ["Wash station", "Handicap accessible"],
        answer: "",
      },
      {
        sl: 6,
        level:
          "Do you know if you’ll have a need for a containment tray, locking hasp, or sanitizer in the unit?",
        field_type: "option",
        field_option: ["Tray", "Locking hasp", "Sanitizer"],
        answer: "",
      },
    ],
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\n\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\n\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\n\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\n\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "standard_rate",
      "delivery_rate",
      "removal_rate",
      "extra_pickup_rate",
      "dry_run_rate",
      "overage_rate",
      "contamination_rate",
      "relocation_rate",
      "exchange_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/front-load.4b787c6e546ca0f462c17a235e8b30ae.svg",
    product_type: [
      {
        id: 113,
        product_id: 1,
        psp_type: "SP",
        psp: 0,
        product_type: "01 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        extra_pickup_rate: 10,
        dry_run_rate: 30,
        overage_rate: 15,
        contamination_rate: 19,
        relocation_rate: 10,
        exchange_rate: 89,
      },
      {
        id: 114,
        product_id: 1,
        psp_type: "SP",
        psp: 0,
        product_type: "02 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        extra_pickup_rate: 10,
        dry_run_rate: 30,
        overage_rate: 15,
        contamination_rate: 19,
        relocation_rate: 10,
        exchange_rate: 89,
      },
      {
        id: 115,
        product_id: 1,
        psp_type: "SP",
        psp: 0,
        product_type: "03 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        extra_pickup_rate: 10,
        dry_run_rate: 30,
        overage_rate: 15,
        contamination_rate: 19,
        relocation_rate: 10,
        exchange_rate: 89,
      },
      {
        id: 116,
        product_id: 1,
        psp_type: null,
        psp: 0,
        product_type: "04 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        extra_pickup_rate: 22,
        dry_run_rate: 6,
        overage_rate: 21,
        contamination_rate: 22,
        relocation_rate: 1,
        exchange_rate: 32,
      },
      {
        id: 117,
        product_id: 1,
        psp_type: null,
        psp: 0,
        product_type: "05 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        extra_pickup_rate: 22,
        dry_run_rate: 6,
        overage_rate: 21,
        contamination_rate: 22,
        relocation_rate: 1,
        exchange_rate: 32,
      },
      {
        id: 118,
        product_id: 1,
        psp_type: "",
        psp: 0,
        product_type: "06 yard",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        extra_pickup_rate: 0,
        dry_run_rate: 0,
        overage_rate: 0,
        contamination_rate: 0,
        relocation_rate: 0,
        exchange_rate: 0,
      },
      {
        id: 119,
        product_id: 1,
        psp_type: "",
        psp: 0,
        product_type: "08 yard",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        extra_pickup_rate: 0,
        dry_run_rate: 0,
        overage_rate: 0,
        contamination_rate: 0,
        relocation_rate: 0,
        exchange_rate: 0,
      },
      {
        id: 120,
        product_id: 1,
        psp_type: "",
        psp: 0,
        product_type: "10 yard",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        extra_pickup_rate: 0,
        dry_run_rate: 0,
        overage_rate: 0,
        contamination_rate: 0,
        relocation_rate: 0,
        exchange_rate: 0,
      },
      {
        id: 121,
        product_id: 1,
        psp_type: "",
        psp: 0,
        product_type: "35 gallon",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        extra_pickup_rate: 0,
        dry_run_rate: 0,
        overage_rate: 0,
        contamination_rate: 0,
        relocation_rate: 0,
        exchange_rate: 0,
      },
      {
        id: 122,
        product_id: 1,
        psp_type: "",
        psp: 0,
        product_type: "55 gallon",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        extra_pickup_rate: 0,
        dry_run_rate: 0,
        overage_rate: 0,
        contamination_rate: 0,
        relocation_rate: 0,
        exchange_rate: 0,
      },
    ],
  },
  {
    id: 2,
    product_name: "Fencing",
    product_abbreviation: "FENCING",
    product_line: "D130",
    status: 1,
    product_description: "des",
    call_script: [
      {
        sl: 1,
        level: "How many Linear Feet are you going to need?",
        field_type: "int",
        field_option: "",
        answer: "",
      },
      {
        sl: 2,
        level: "Would you like 6ft high fencing or 8 foot high?",
        field_type: "option",
        field_option: ["Yes", "No"],
        answer: "",
      },
      {
        sl: 3,
        level: "Are you looking for Panels on Stands or Post-Driven?",
        field_type: "option",
        field_option: ["Stands", "Post-Driven"],
        answer: "",
      },
      {
        sl: 4,
        level:
          "Would you be in any need of Windscreen or Sand Bags to secure your panels on stands?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 5,
        level: "Would you need a Personnel or Equipment Gate(s)?",
        field_type: "option",
        field_option: ["Personnel", "Equipment Gate(s)"],
        answer: "",
      },
      {
        sl: 6,
        level: "How long will you need the fencing in place?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 7,
        level: "What is your timeframe for delivery?",
        field_type: "date",
        field_option: "",
        answer: "",
      },
      {
        sl: 8,
        level: "Is this a Prevailing Wage/Government project?",
        field_type: "option",
        field_option: ["Wage", "Government"],
        answer: "",
      },
    ],
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\r\n\r\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\r\n\r\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\r\n\r\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\r\n\r\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "cycle_time",
      "standard_rate",
      "delivery_rate",
      "removal_rate",
      "secondary_cycle_time",
      "secondary_rental_rate",
      "dry_run_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/frencing.fd68b3a1beb53b1c0e9d8e38cece1112.svg",
    product_type: [
      {
        id: 68,
        product_id: 2,
        psp_type: "SP",
        psp: 0,
        product_type: "Chain Link",
        quantity: 0,
        cycle_time: 10,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        secondary_cycle_time: 10,
        secondary_rental_rate: 10,
        dry_run_rate: 30,
      },
      {
        id: 69,
        product_id: 2,
        psp_type: "SP",
        psp: 0,
        product_type: "Barricade",
        quantity: 0,
        cycle_time: 10,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        secondary_cycle_time: 10,
        secondary_rental_rate: 10,
        dry_run_rate: 30,
      },
      {
        id: 70,
        product_id: 2,
        psp_type: "SP",
        psp: 0,
        product_type: "Traffic Control",
        quantity: 0,
        cycle_time: 10,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        secondary_cycle_time: 10,
        secondary_rental_rate: 10,
        dry_run_rate: 30,
      },
      {
        id: 71,
        product_id: 2,
        psp_type: "SP",
        psp: 0,
        product_type: "Bicycle",
        quantity: 0,
        cycle_time: 10,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        secondary_cycle_time: 10,
        secondary_rental_rate: 10,
        dry_run_rate: 30,
      },
      {
        id: 72,
        product_id: 2,
        psp_type: "SP",
        psp: 0,
        product_type: "Silt",
        quantity: 0,
        cycle_time: 10,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        secondary_cycle_time: 10,
        secondary_rental_rate: 10,
        dry_run_rate: 30,
      },
    ],
  },
  {
    id: 3,
    product_name: "Other",
    product_abbreviation: "OTHER",
    product_line: "D150",
    status: 1,
    product_description: "Grease Trap",
    call_script: [
      {
        sl: 1,
        level:
          "May I ask if you are looking to rent for a jobsite or an event?",
        field_type: "option",
        field_option: ["Event", "Jobsite"],
        answer: "",
      },
      {
        sl: 2,
        level: "How many attendees do you plan on having?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 3,
        level: "What is the duration and day of your event?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 4,
        level:
          "Will you have a need for hand wash station or handicap accessible unit?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 5,
        level:
          "Will you have a need for hand wash station or handicap accessible unit?",
        field_type: "option",
        field_option: ["Wash station", "Handicap accessible"],
        answer: "",
      },
      {
        sl: 6,
        level:
          "Do you know if you’ll have a need for a containment tray, locking hasp, or sanitizer in the unit?",
        field_type: "option",
        field_option: ["Tray", "Locking hasp", "Sanitizer"],
        answer: "",
      },
    ],
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\r\n\r\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\r\n\r\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\r\n\r\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\r\n\r\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "standard_rate",
      "delivery_rate",
      "dry_run_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/portable_office_storage_combo.5b5baf1055d10f3b5ec4878e27bd922f.svg",
    product_type: [
      {
        id: 132,
        product_id: 3,
        psp_type: "SP",
        psp: 0,
        product_type: "Other",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        dry_run_rate: 30,
      },
    ],
  },
  {
    id: 4,
    product_name: "Perm Roll-Off/Compactor",
    product_abbreviation: "PERM-RO",
    product_line: "D320",
    status: 1,
    product_description: null,
    call_script: [
      {
        sl: 1,
        level:
          "May I ask if you are looking to rent for a jobsite or an event?",
        field_type: "option",
        field_option: ["Event", "Jobsite"],
        answer: "",
      },
      {
        sl: 2,
        level: "How many attendees do you plan on having?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 3,
        level: "What is the duration and day of your event?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 4,
        level:
          "Will you have a need for hand wash station or handicap accessible unit?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 5,
        level:
          "Will you have a need for hand wash station or handicap accessible unit?",
        field_type: "option",
        field_option: ["Wash station", "Handicap accessible"],
        answer: "",
      },
      {
        sl: 6,
        level:
          "Do you know if you’ll have a need for a containment tray, locking hasp, or sanitizer in the unit?",
        field_type: "option",
        field_option: ["Tray", "Locking hasp", "Sanitizer"],
        answer: "",
      },
    ],
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\r\n\r\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\r\n\r\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\r\n\r\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\r\n\r\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "frequency",
      "standard_rate",
      "delivery_rate",
      "removal_rate",
      "dry_run_rate",
      "service_rate",
      "service_rate_after_hours",
      "relocation_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/portable-toilet.7d3c9090de31a9aaa24d9f58abacce5d.svg",
    product_type: [
      {
        id: 96,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "10 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 97,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "12 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 98,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "15 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 99,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "18 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 100,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "20 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 101,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "25 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 102,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "30 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 103,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "35 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 104,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "40 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 105,
        product_id: 4,
        psp_type: "",
        psp: 0,
        product_type: "42 yard",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
    ],
  },
  {
    id: 5,
    product_name: "Portable Toilet",
    product_abbreviation: "PT",
    product_line: "D110",
    status: 1,
    product_description: null,
    call_script: [
      {
        sl: 1,
        level:
          "May I ask if you are looking to rent for a jobsite or an event?",
        field_type: "option",
        field_option: ["Event", "Jobsite"],
        answer: "",
      },
      {
        sl: 2,
        level: "How many attendees do you plan on having?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 3,
        level: "What is the duration and day of your event?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 4,
        level:
          "Will you have a need for hand wash station or handicap accessible unit?",
        field_type: "text",
        field_option: "",
        answer: "",
      },
      {
        sl: 5,
        level:
          "Will you have a need for hand wash station or handicap accessible unit?",
        field_type: "option",
        field_option: ["Wash station", "Handicap accessible"],
        answer: "",
      },
      {
        sl: 6,
        level:
          "Do you know if you’ll have a need for a containment tray, locking hasp, or sanitizer in the unit?",
        field_type: "option",
        field_option: ["Tray", "Locking hasp", "Sanitizer"],
        answer: "",
      },
    ],
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\r\n\r\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\r\n\r\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\r\n\r\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\r\n\r\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "frequency",
      "standard_rate",
      "delivery_rate",
      "removal_rate",
      "dry_run_rate",
      "service_rate",
      "service_rate_after_hours",
      "relocation_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/portable-toilet.7d3c9090de31a9aaa24d9f58abacce5d.svg",
    product_type: [
      {
        id: 44,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Standard Toilet",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 45,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "ADA Toilet",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 46,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Hand Wash Station",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 47,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Standard Toilet w/Sink",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 48,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Standard Toilet w/Flush",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 49,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Standard Toilet w/Flush&Sink",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 50,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Freshwater Holding Tank",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 51,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Wastewater Holding Tank",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 52,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Trailer",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 53,
        product_id: 5,
        psp_type: "",
        psp: 0,
        product_type: "Sanitizer Station",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
    ],
  },
  {
    id: 6,
    product_name: "Roll-Off",
    product_abbreviation: "RO",
    product_line: "D120",
    status: 1,
    product_description: null,
    call_script: null,
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\r\n\r\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\r\n\r\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\r\n\r\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\r\n\r\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "standard_rate",
      "delivery_rate",
      "removal_rate",
      "dry_run_rate",
      "relocation_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/storage.2f859db9d1f8c5edfa31c25187d6736f.svg",
    product_type: [
      {
        id: 73,
        product_id: 6,
        psp_type: "SP",
        psp: 0,
        product_type: "10 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        dry_run_rate: 30,
        relocation_rate: 10,
      },
      {
        id: 74,
        product_id: 6,
        psp_type: "SP",
        psp: 0,
        product_type: "12 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        dry_run_rate: 30,
        relocation_rate: 10,
      },
      {
        id: 75,
        product_id: 6,
        psp_type: "SP",
        psp: 0,
        product_type: "15 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        dry_run_rate: 30,
        relocation_rate: 10,
      },
      {
        id: 76,
        product_id: 6,
        psp_type: "SP",
        psp: 0,
        product_type: "18 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        dry_run_rate: 30,
        relocation_rate: 10,
      },
      {
        id: 77,
        product_id: 6,
        psp_type: null,
        psp: 0,
        product_type: "20 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        relocation_rate: 1,
      },
      {
        id: 78,
        product_id: 6,
        psp_type: null,
        psp: 0,
        product_type: "25 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        relocation_rate: 1,
      },
      {
        id: 79,
        product_id: 6,
        psp_type: null,
        psp: 0,
        product_type: "30 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        relocation_rate: 1,
      },
      {
        id: 80,
        product_id: 6,
        psp_type: null,
        psp: 0,
        product_type: "35 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        relocation_rate: 1,
      },
      {
        id: 81,
        product_id: 6,
        psp_type: null,
        psp: 0,
        product_type: "40 yard",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        relocation_rate: 1,
      },
      {
        id: 82,
        product_id: 6,
        psp_type: null,
        psp: 0,
        product_type: "Trash Trailer",
        quantity: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        relocation_rate: 1,
      },
    ],
  },
  {
    id: 7,
    product_name: "Storage Containers/Mobile Offices",
    product_abbreviation: "STORAGE",
    product_line: "D140",
    status: 1,
    product_description: null,
    call_script: null,
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\r\n\r\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\r\n\r\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\r\n\r\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\r\n\r\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "standard_rate",
      "delivery_rate",
      "removal_rate",
      "dry_run_rate",
      "relocation_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/equipment.412059f12354b40e304ac6f7b7e8c984.svg",
    product_type: [
      {
        id: 84,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "20 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 85,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "40 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 86,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "20 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 87,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "40 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 88,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "20 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 89,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "40 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 90,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "10 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 91,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "12 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 92,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "14 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
      {
        id: 93,
        product_id: 7,
        psp_type: "",
        psp: 0,
        product_type: "16 ft",
        quantity: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        relocation_rate: 0,
      },
    ],
  },
  {
    id: 8,
    product_name: "Equipment Rentals",
    product_abbreviation: "EQUIPMENT",
    product_line: "D150",
    status: 1,
    product_description: null,
    call_script: null,
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\r\n\r\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\r\n\r\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\r\n\r\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\r\n\r\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "frequency",
      "standard_rate",
      "delivery_rate",
      "removal_rate",
      "dry_run_rate",
      "service_rate",
      "service_rate_after_hours",
      "relocation_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/compactor.9eb3984395f3a685f1d634fb89be64a8.svg",
    product_type: [
      {
        id: 144,
        product_id: 8,
        psp_type: null,
        psp: 0,
        product_type: "32 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        service_rate: 32,
        service_rate_after_hours: 32,
        relocation_rate: 1,
      },
      {
        id: 138,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "30 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 139,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "34 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 140,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "40 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 141,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "60 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 142,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "45 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 143,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "19 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 145,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "26 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 146,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "40 ft",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 147,
        product_id: 8,
        psp_type: "",
        psp: 0,
        product_type: "Industrial",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
    ],
  },
  {
    id: 9,
    product_name: "Other Services",
    product_abbreviation: "OS",
    product_line: "D150",
    status: 1,
    product_description: null,
    call_script: null,
    script_tips:
      "<p><b>SK29 May I ask if you are looking to rent for a jobsite or an event?</b></p>\r\n\r\n<p><b>Event:</b> How many attendees do you plan on having? What is the duration and day of your event? What type of event are you having? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit?</p>\r\n\r\n<p><b>Job Site:</b> How many employees will be onsite? How many hours per week will they be working? Will you have a need for hand wash station or handicap accessible unit? Do you know if you&rsquo;ll have a need for a containment tray, locking hasp, or sanitizer in the unit? How often were you looking to get the units serviced/cleaned? 1x/week service is the average service minimum, but we can look into other options if that makes more sense for your needs.</p>\r\n\r\n<p><b>SK12 Will you have a need for: temporary fencing__ roll-offs__ storage container__</b></p>\r\n\r\n<p></b>SK13 What is your timeframe for delivery? Do you know how long you will need to rent the unit?</b></p>",
    wizard_field: [
      "psp",
      "product_name",
      "quantity",
      "frequency",
      "standard_rate",
      "delivery_rate",
      "removal_rate",
      "dry_run_rate",
      "service_rate",
      "service_rate_after_hours",
      "relocation_rate",
    ],
    product_image:
      "https://dev001.goomka.com/static/media/portable_office_storage_combo.5b5baf1055d10f3b5ec4878e27bd922f.svg",
    product_type: [
      {
        id: 161,
        product_id: 9,
        psp_type: "SP",
        psp: 0,
        product_type: "Cleaning",
        quantity: 0,
        frequency: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        dry_run_rate: 30,
        service_rate: 11,
        service_rate_after_hours: 10,
        relocation_rate: 10,
      },
      {
        id: 162,
        product_id: 9,
        psp_type: "SP",
        psp: 0,
        product_type: "Purchase",
        quantity: 0,
        frequency: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        dry_run_rate: 30,
        service_rate: 11,
        service_rate_after_hours: 10,
        relocation_rate: 10,
      },
      {
        id: 164,
        product_id: 9,
        psp_type: "SP",
        psp: 0,
        product_type: "Power Washing",
        quantity: 0,
        frequency: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        dry_run_rate: 30,
        service_rate: 11,
        service_rate_after_hours: 10,
        relocation_rate: 10,
      },
      {
        id: 165,
        product_id: 9,
        psp_type: "SP",
        psp: 0,
        product_type: "Other",
        quantity: 0,
        frequency: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 10,
        dry_run_rate: 30,
        service_rate: 11,
        service_rate_after_hours: 10,
        relocation_rate: 10,
      },
      {
        id: 166,
        product_id: 9,
        psp_type: null,
        psp: 0,
        product_type: "Junk Removal",
        quantity: 0,
        frequency: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        service_rate: 32,
        service_rate_after_hours: 32,
        relocation_rate: 1,
      },
      {
        id: 178,
        product_id: 9,
        psp_type: null,
        psp: 0,
        product_type: "Grease",
        quantity: 0,
        frequency: 0,
        standard_rate: 100,
        delivery_rate: 20,
        removal_rate: 2,
        dry_run_rate: 6,
        service_rate: 32,
        service_rate_after_hours: 32,
        relocation_rate: 1,
      },
      {
        id: 169,
        product_id: 9,
        psp_type: "",
        psp: 0,
        product_type: "",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 182,
        product_id: 9,
        psp_type: "",
        psp: 0,
        product_type: "Other",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 183,
        product_id: 9,
        psp_type: "",
        psp: 0,
        product_type: "Power Washing",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
      {
        id: 184,
        product_id: 9,
        psp_type: "",
        psp: 0,
        product_type: "Power Washings",
        quantity: 0,
        frequency: 0,
        standard_rate: 0,
        delivery_rate: 0,
        removal_rate: 0,
        dry_run_rate: 0,
        service_rate: 0,
        service_rate_after_hours: 0,
        relocation_rate: 0,
      },
    ],
  },
];
