import {
  acceptList,
  accessoriesList,
  cycleTimeList,
  frequencyList,
  lengthList,
  portableToiletCategoryList,
  rentalProtectionList,
  restroomTrailerList,
  saleTempList,
  serviceDaysList,
} from "../../../static-data";
import { commonProductMetadata } from "../common";

export function ptProductMetadataFields() {
  const formMetaData = [
    ...commonProductMetadata(),
    {
      type: "select",
      label: "Category",
      name: "category",
      required: true,
      validation: { required: "Category is required" },
      options: portableToiletCategoryList(),
      width: 6,
    },
    {
      type: "text",
      label: "Event Type & Time",
      name: "event_type_time",
      validation: {},
      showCondition: (state: { category?: string }) =>
        state.category === "Event",
      width: 6,
    },
    {
      type: "specialSelect",
      label: "Product Type",
      name: "product_type",
      required: true,
      validation: { required: "Product type is required" },
      options: {},
      width: 6,
    },
    {
      type: "number",
      label: "Gallons for holding tanks",
      name: "gallons_for_holding_tanks",
      validation: {},
      width: 6,
    },
    {
      type: "multiselect",
      label: "Accessories",
      name: "accessories",
      validation: {},
      options: accessoriesList(),
      width: 6,
      maxtagcount: 1,
    },
    {
      type: "checkbox",
      label: "Winter Service Charge",
      name: "winter_service_charge",
      validation: {},
      marginTop: 2,
      width: 4,
    },
    {
      type: "number",
      label: "Quantity",
      name: "quantity",
      required: true,
      validation: { required: "Quantity is required" },
      width: 4,
    },
    {
      type: "select",
      label: "Frequency of Service",
      name: "frequency",
      required: true,
      validation: { required: "Frequency is required" },
      options: frequencyList(),
      width: 4,
    },
    {
      type: "select",
      label: "Cycle Time",
      name: "cycle_time",
      validation: {},
      options: cycleTimeList(),
      width: 4,
    },
    {
      type: "select",
      label: "Water Accessibility",
      name: "water_accessibility",
      validation: {},
      options: acceptList(),
      showCondition: (state: { category?: string; productType?: number }) =>
        state.productType === 52 || state.productType === 64,
      width: 4,
    },
    {
      type: "select",
      label: "Power Accessibility",
      name: "power_accessibility",
      validation: {},
      options: acceptList(),
      showCondition: (state: { productType?: number }) =>
        state.productType === 52 || state.productType === 64,
      width: 4,
    },
    {
      type: "select",
      label: "Restroom Trailer Type",
      name: "restroom_trailer_type",
      validation: {},
      options: restroomTrailerList(),
      showCondition: (state: { productType?: number }) =>
        state.productType === 52 || state.productType === 64,
      width: 4,
    },
    {
      type: "date",
      label: "Delivery Date",
      name: "delivery_date",
      required: true,
      validation: { required: "Delivery Date is required" },
      width: 4,
    },
    {
      type: "date",
      label: "Removal Date",
      name: "removal_date",
      validation: {},
      width: 4,
    },
    {
      type: "select",
      label: "Length of Project",
      name: "length_of_project",
      validation: {},
      options: lengthList(),
      width: 4,
    },
    {
      type: "multiselect",
      label: "Service Day(s)",
      name: "service_days",
      validation: {},
      options: serviceDaysList(),
      width: 4,
    },
    {
      type: "date",
      label: "Service Day(s) Verified on",
      name: "service_days_verified_on",
      validation: {},
      width: 4,
    },
    {
      type: "select",
      label: "Rental Protection",
      name: "rental_protection",
      required: true,
      validation: { required: "This field is required" },
      options: rentalProtectionList(),
      width: 6,
    },
    {
      type: "select",
      label: "Sale Temperature",
      name: "sale_temperature",
      required: true,
      validation: { required: "Sale Temperature is required" },
      options: saleTempList(),
      width: 6,
    },
    {
      type: "number",
      label: "How many employees will be onsite?",
      name: "employees",
      validation: {},
      width: 6,
    },
    {
      type: "number",
      label: "How many hours per week will they be working?",
      name: "hours_per_week",
      validation: {},
      width: 6,
    },
    {
      type: "checkbox",
      label: "Multiple Shifts",
      name: "multiple_shifts",
      validation: {},
      marginTop: 0.5,
      width: 3,
    },
    {
      type: "notes",
      label: "Notes",
      name: "notes",
      validation: {},
      width: 12,
    },
    {
      type: "instructions",
      isField: false,
      label: "",
      name: "",
      validation: {},
      width: 12,
    },
  ];
  return formMetaData;
}
